-- Query to extract open RIS
# Query
SELECT       
  s1.PICK_SLIP_NO,
  LISTAGG(s1.BATCH_NO, ',') WITHIN GROUP (ORDER BY s1.BATCH_NO) BATCH_NO,
  s1.REQUESTING_PRODUCTION,
  s1.ITEM_CODE,
  s1.UOM,
  SUM(s1.REQUIRED_QUANTITY) REQUIRED_QUANTITY,
  s1.INVENTORY_ITEM_ID,
  NVL(mo.TOTAL_ONHAND_QTY, 0) - NVL(mr.RESERVATION_QUANTITY, 0) ONHAND_QUANTITY
 
FROM 
   (
    SELECT DISTINCT
      GMH.ATTRIBUTE1 "PICK_SLIP_NO",
      GMH.BATCH_NO,
      MTO.ORGANIZATION_CODE "REQUESTING_PRODUCTION",
      MSIB.SEGMENT1 "ITEM_CODE",
      UOM.UNIT_OF_MEASURE "UOM",
      GMD.PLAN_QTY "REQUIRED_QUANTITY",
      GMD.INVENTORY_ITEM_ID,
      GMD.DTL_UM,
      GMD.ORGANIZATION_ID
    FROM
      GME_BATCH_HEADER GMH,
      GME_MATERIAL_DETAILS GMD,
      MTL_PARAMETERS MTO,
      MTL_SYSTEM_ITEMS_B MSIB,
      MTL_UNITS_OF_MEASURE_VL UOM
    WHERE
      GMH.BATCH_ID = GMD.BATCH_ID
      AND GMD.ORGANIZATION_ID = MTO.ORGANIZATION_ID
      AND GMD.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
      AND UOM.UOM_CODE = GMD.DTL_UM
      AND GMH.BATCH_STATUS = 1
      AND GMH.ATTRIBUTE1 IS NOT NULL
      AND NOT EXISTS (SELECT 1
                      FROM GME_BATCH_HEADER gmh2
                      WHERE gmh2.BATCH_NO = GMH.BATCH_NO
                      AND GMH2.BATCH_STATUS <> 1)
    ORDER BY
      GMH.ATTRIBUTE1 ) S1
   LEFT JOIN 
      (SELECT
          INVENTORY_ITEM_ID,
          ORGANIZATION_ID,
          UOM,
          SUM(ON_HAND) AS TOTAL_ONHAND_QTY
        FROM MTL_ONHAND_TOTAL_MWB_V
        GROUP BY
          INVENTORY_ITEM_ID,
          ORGANIZATION_ID,
          UOM ) MO
      ON MO.INVENTORY_ITEM_ID = S1.INVENTORY_ITEM_ID
      AND MO.ORGANIZATION_ID = S1.ORGANIZATION_ID
      AND MO.UOM = S1.DTL_UM
   LEFT JOIN (SELECT
              INVENTORY_ITEM_ID,
              ORGANIZATION_ID,
              PRIMARY_UOM_CODE,
              SUM(RESERVATION_QUANTITY) AS RESERVATION_QUANTITY
            FROM MTL_RESERVATIONS
            GROUP BY
              INVENTORY_ITEM_ID,
              ORGANIZATION_ID,
              PRIMARY_UOM_CODE) mr
       ON Mr.INVENTORY_ITEM_ID = S1.INVENTORY_ITEM_ID
      AND Mr.ORGANIZATION_ID = S1.ORGANIZATION_ID
      AND Mr.PRIMARY_UOM_CODE = S1.DTL_UM

-- Response
{'PICK_SLIP_NO': '70010829',  'BATCH_NO': '10086370', 'REQUESTING_PRODUCTION': 'WDB', 'ITEM_CODE': 'SSM-1149W',\
 'UOM': 'Bag', 'REQUIRED_QUANTITY': 39.78806, 'INVENTORY_ITEM_ID': 111006, 'ONHAND_QUANTITY': 0, mr.RESERVATION_QUANTITY}